### ISSUE TITLE
Forced Combination error

### ISSUE THREAD

**Issue by nftchef** [nftchef/art-engine#14]
Error being thrown in the latest version when forced  combination is not empty, using the sample layers

```
Setting up the folling forced combinations for floral:  MetallicShades Golden Sakura
Force picking MetallicShades/n
(node:92974) UnhandledPromiseRejectionWarning: ReferenceError: element is not defined
    at pickRandomElement (/Users/lk-user/Documents/hashlips_art_engine/4/art-engine/src/main.js:466:53)
    at /Users/lk-user/Documents/hashlips_art_engine/4/art-engine/src/main.js:641:5
    at Array.forEach (<anonymous>)
    at createDna (/Users/lk-user/Documents/hashlips_art_engine/4/art-engine/src/main.js:639:11)
    at startCreating (/Users/lk-user/Documents/hashlips_art_engine/4/art-engine/src/main.js:807:20)
    at /Users/lk-user/Documents/hashlips_art_engine/4/art-engine/index.js:13:3
    at Object.<anonymous> (/Users/lk-user/Documents/hashlips_art_engine/4/art-engine/index.js:14:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
```

**Comment by rpgraul** [comment]
Hi bro, i got the same error, so on main.js at line 466 i changed the `${element.zindex}` for `${forcedPick.zindex}` and worked for me
