### ISSUE TITLE
An error with Zindex

### ISSUE THREAD

**Issue by Matiserrano99** [nftchef/art-engine#147]
Hello! recently i start to test this amazing feature, and works perfectly but today i cant stop of get this error. I thought maybe i insert a wrong z# number or i have a name problem but try to catch and nothing.

  return z ? parseInt(z[0].match(/-?\d+/)[0]) : null;
                                         ^

TypeError: Cannot read properties of null (reading '0')
    at parseZIndex (D:\trabajo\DESURE\NFT\Changos\Generacion Nfts\Programacion\art-engine-nested-folder-structure\src\main.js:140:42)
    at D:\trabajo\DESURE\NFT\Changos\Generacion Nfts\Programacion\art-engine-nested-folder-structure\src\main.js:602:20
    at Array.reduce (<anonymous>)
    at sortLayers (D:\trabajo\DESURE\NFT\Changos\Generacion Nfts\Programacion\art-engine-nested-folder-structure\src\main.js:601:22)
    at D:\trabajo\DESURE\NFT\Changos\Generacion Nfts\Programacion\art-engine-nested-folder-structure\src\main.js:655:26
    at Array.forEach (<anonymous>)
    at createDna (D:\trabajo\DESURE\NFT\Changos\Generacion Nfts\Programacion\art-engine-nested-folder-structure\src\main.js:644:11)
    at startCreating (D:\trabajo\DESURE\NFT\Changos\Generacion Nfts\Programacion\art-engine-nested-folder-structure\src\main.js:814:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by nftchef** [comment]
there's a possibility that it's trying to read a hidden file (like `Desktop.ini`), OR, there could be a typo in one of the files that uses `z`. Without seeing you files it's hard to debug. did you figure it out?
