### ISSUE TITLE
rarityData.js non-functional

### ISSUE THREAD

**Issue by jskoizumi** [nftchef/art-engine#23]
upon running it seems to be looking for an undefined 'elemnts' any insight on this error?

```
j@Js-MacBook-Pro NFT Chef LG % node '/Users/j/Desktop/LonerGirl/NFT Chef LG/utils/rarityData.js'
/Users/j/Desktop/LonerGirl/NFT Chef LG/src/config.js
/Users/j/Desktop/LonerGirl/NFT Chef LG/src/config.js
/Users/j/Desktop/LonerGirl/NFT Chef LG/utils/rarityData.js:134
      rarityDataTraits.elements.forEach((rarityDataTrait) => {
                       ^

TypeError: Cannot read properties of undefined (reading 'elements')
    at /Users/j/Desktop/LonerGirl/NFT Chef LG/utils/rarityData.js:134:24
    at Array.forEach (<anonymous>)
    at /Users/j/Desktop/LonerGirl/NFT Chef LG/utils/rarityData.js:127:6
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/j/Desktop/LonerGirl/NFT Chef LG/utils/rarityData.js:122:6)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
j@Js-MacBook-Pro NFT Chef LG % 
```

**Comment by j-greig** [comment]
Did you find the cause for this or a fix? 

Have same problem. Thanks!
