### ISSUE TITLE
SyntaxError when building: "Unexpected token ." in main.js

### ISSUE THREAD

**Issue by j-greig** [nftchef/art-engine#33]
Running the build compile on the default package gave the error below.

I have manually installed eslint as NPM was complaining it was missing when I ran the install.

My Node version is v11.15.0

Sorry if this is an obvious fix I've not done anything from the command line for a long time!

[UPDATE: the build script works fine if I comment out anything related to `layer.sublayerOptions` in main.js]

```
/strongbots-generator/src/main.js:126
  if (layer.sublayerOptions?.[sublayer]) {
                            ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:760:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/strongbots-generator/index.js:6:39)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hashlips_art_engine@1.0.6 build: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hashlips_art_engine@1.0.6 build script
```

**Comment by nftchef** [comment]
hey @j-greig !!
This is a node version issue, thanks for providing that!

the conditional object property `?.` syntax is not supported until later versions of Node. You will need to upgrade to the latest version (or at least 14 I believe)

**Comment by j-greig** [comment]
Ah thank you! Fixed.
